#cloud-config
packages:
  - ntp
runcmd:
  - sudo mkdir -p /opt/bingo/logs/ && sudo chown -R ubuntu:ubuntu /opt/bingo/logs/
  - sudo sed -i '20 a */1 * * * * ubuntu :> /opt/bingo/logs/main.log' /etc/crontab
  - sudo systemctl restart cron
